**To avoid the internal error due to one_hot function**
 
error message : InternalError: Blas SGEMM launch failed :
1. restart the Kernel
2. if 1 does not work, try below

I encountered this error while I was trying to port the jupyter notebook script from python2 to python3.

referred sites:
 
https://github.com/tensorflow/tensorflow/issues/6509
http://stackoverflow.com/questions/37337728/tensorflow-internalerror-blas-sgemm-launch-failed (the last and latest answer rings the bell for me)

In [1]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import make_moons, make_blobs

batch_size = 16
Xs, ys = make_blobs(300, centers=[[0, 0], [0, 1]], cluster_std=0.2)
D_ind = np.hstack([np.zeros(batch_size // 2, dtype=np.int32),
                              np.ones(batch_size // 2, dtype=np.int32)])

'''
1st Method
'''
with tf.device("/cpu:0"):
    Y = tf.one_hot(ys, 2)
    D = tf.one_hot(D_ind, 2)

sess = tf.Session()
#print(ys)
#print(Y)
print(D_ind)
print(D)
sess.close()

[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[[ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]]


In [ ]:
    
'''
2nd Method
'''

#Instead of Y = tf.one_hot(ys, 2)
num_labels = 2
sparse_labels = tf.reshape(ys, [-1, 1])
derived_size = tf.shape(sparse_labels)[0]
indices = tf.reshape(tf.range(0, derived_size, 1), [-1, 1])
concated = tf.concat(1, [indices, sparse_labels])
outshape = tf.concat(0, [tf.reshape(derived_size, [1]), tf.reshape(num_labels, [1])])
Y = tf.sparse_to_dense(concated, outshape, 1.0, 0.0)

#Instead of D = tf.one_hot(D_ind, 2)
sparse_labels_D = tf.reshape(D_ind, [-1, 1])
derived_size_D = tf.shape(sparse_labels_D)[0]
indices_D = tf.reshape(tf.range(0, derived_size_D, 1), [-1, 1])
concated_D = tf.concat(1, [indices_D, sparse_labels_D])
outshape_D = tf.concat(0, [tf.reshape(derived_size_D, [1]), tf.reshape(num_labels, [1])])
D = tf.sparse_to_dense(concated_D, outshape_D, 1.0, 0.0)


#print(ys)
#print(Y)

print(D_ind)
print(sess.run(D))


In [3]:
'''
3rd Method
'''
def oh_encoding(label, num_classes):        
    result = np.zeros((len(label), num_classes),dtype=np.int32)
    result[np.arange(len(label)), label] = 1
    #print(result)
    return result
print(ys)
print(oh_encoding(ys, 2))

[0 1 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0
 0 1 1 1 0 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 1 1 1
 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1
 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 1 0
 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1
 1 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1
 0 1 0 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1
 0 0 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0
 0 0 1 0]
[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1